### ISSUE TITLE
Incompatible with Simple Fog Control and Custom Fog

### ISSUE THREAD

**Issue by SplendidAlakey** [Dev0Louis/FoggyBorder#2]
**MC** 1.20.4
**Foggy Border** 1.1
**[Simple Fog Control](https://modrinth.com/mod/simplefog)** 1.4.0
or
**[Custom Fog](https://modrinth.com/mod/custom-fog)** 2.2.0

With either of these mods installed, the only Foggy Border feature that works is removing the blue lines, while the fog effect is not working at all. The logs are essentially empty so not attaching any.

**Comment by Dev0Louis** [comment]
Thank you for reporting the issue. 
The Problem seems to be the implementation of their mixins. I will try to reach out to the Devs to look if a change that will make the mods work together can be done.

**Comment by Dev0Louis** [comment]
As I can't do anything about their broken implementation I will close this issue.
